site_name: Jake Anto

theme:
  name: material
  language: en
  icon:
    logo: material/laptop

  features:
    - content.action.view
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - blog:
      blog_toc: false
      post_url_format: "{slug}"
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - social

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/JakeAnto
      name: Jake Anto on GitHub

nav:
  - About me:
    - index.md
  - Blog:
    - blog/index.md

edit_uri: https://github.com/jakeanto/jakeanto.github.io/edit/main/docs/
copyright: This work is licensed under <not decided yet>