site_name: Jake Anto

theme:
  name: material
  custom_dir: overrides
  language: en
  icon:
    logo: material/laptop

  features:
    - content.action.view
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      blog_toc: false
      post_url_format: "{slug}"
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - social
  - glightbox  

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/j-eo
      name: Jake Anto on GitHub

nav:
  - About Me:
    - index.md
  - Blog:
    - blog/index.md

edit_uri: https://github.com/j-eo/j-eo.github.io/edit/main/docs/

copyright: This work © 2023 by Jake Anto is licensed under <a href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>